lib/menu_planner_web/router.ex
defmodule MenuPlannerWeb.Router do
  use MenuPlannerWeb, :router
  import Phoenix.LiveDashboard.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug MenuPlannerWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :token_auth do
    plug MenuPlannerWeb.Auth.Pipeline
  end

  scope "/", MenuPlannerWeb do
    pipe_through :browser

    get "/", PageController, :index

    get "/login", SessionController, :new
    post "/login", SessionController, :create
    get "/logout", SessionController, :delete
  end

  scope "/", MenuPlannerWeb do
    pipe_through [:browser, :authenticate_user]

    live_dashboard "/dashboard", metrics: MenuPlannerWeb.Telemetry

    resources "/menus", MenuController, except: [:delete]
    resources "/users", UserController, except: [:delete]
  end

  scope "/api", MenuPlannerWeb, as: :api do
    pipe_through :api

    scope "/v1", Api.V1, as: :v1 do
      post "/login", AuthController, :login
    end

    scope "/v1", Api.V1, as: :v1 do
      pipe_through :token_auth

      resources "/service_types", ServiceTypeController, only: [:index]

      resources "/menus", MenuController, only: [:index] do
        resources "/meal_services", MealServiceController, only: [:index]
      end

      resources "/meal_services", MealServiceController, only: [:show, :create, :update]
    end
  end

  scope "/api/swagger" do
    forward "/", PhoenixSwagger.Plug.SwaggerUI,
      otp_app: :menu_planner,
      swagger_file: "swagger.json"
  end

  def swagger_info do
    %{
      info: %{
        version: "1.0",
        title: "Menu Planner"
      },
      tags: [],
      securityDefinitions: %{
        Bearer: %{
          type: "apiKey",
          name: "Authorization",
          description:
            "API Token must be provided via `Authorization: Bearer <api_token>` header",
          in: "header"
        }
      },
      consumes: ["application/json"],
      produces: ["application/json"]
    }
  end
end

lib/menu_planner_web/views/layout_view.ex
defmodule MenuPlannerWeb.LayoutView do
  use MenuPlannerWeb, :view
end

lib/menu_planner_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Menu Planner</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-md navbar-dark bg-dark" role="navigation">
        <div class="container">
          <%= link "Menu Planner", to: Routes.page_path(@conn, :index), class: "navbar-brand" %>
          <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav">
              <%= if @current_user do %>
                <li class="navbar-item">
                  <%= link "Users", to: Routes.user_path(@conn, :index), class: "nav-link" %>
                </li>
                <li class="navbar-item">
                  <%= link "Menus", to: Routes.menu_path(@conn, :index), class: "nav-link" %>
                </li>
              <% end %>
            </ul>
            <ul class="navbar-nav ml-auto">
              <%= if @current_user do %>
                <%= if function_exported?(Routes, :live_dashboard_path, 2) do %>
                  <li class="navbar-item">
                    <%= link  to: Routes.live_dashboard_path(@conn, :home), target: "_blank", class: "nav-link" do %>
                      <i class="fas fa-tachometer-alt"></i>
                    <% end %>
                  </li>
                <% end %>
                <li class="navbar-item">
                  <%= link to: Routes.session_path(@conn, :delete), class: "nav-link" do %>
                    <i class="fas fa-sign-out-alt"></i> Log out
                  <% end %>
                </li>
              <% else %>
                <li class="navbar-item">
                  <%= link to: Routes.session_path(@conn, :new), class: "nav-link" do %>
                    <i class="fas fa-sign-in-alt"></i> Log in
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="pt-1 pb-5">
        <%= if msg = get_flash(@conn, :info) do %>
          <div class="alert alert-info alert-dismissible" role="alert">
            <button class="close" type="button" data-dismiss="alert">
              <span>&times;</span>
            </button>
            <%= msg %>
          </div>
        <% end %>
        <%= if msg = get_flash(@conn, :error) do %>
          <div class="alert alert-danger alert-dismissible" role="alert">
            <button class="close" type="button" data-dismiss="alert">
              <span>&times;</span>
            </button>
            <%= msg %>
          </div>
        <% end %>
      </div>
      <%= @inner_content %>
    </main>
  </body>
</html>